Import libraries

In [17]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris, load_wine
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

load dataset

In [18]:
data = load_iris()
# DataFrame Creation
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

Train-Test Split

In [19]:
# Splitting the data into features and target
X = df.drop('target', axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

Model Training:
Trained three classifiers: GaussianNB, LogisticRegression, and DecisionTreeClassifier

In [20]:
# Training GaussianNB classifier
gnb = GaussianNB()
gnb.fit(X_train, y_train)

# prediction
y_pred_gnb = gnb.predict(X_test)

In [21]:
# Evaluating GaussianNB performance
accuracy_gnb = accuracy_score(y_test, y_pred_gnb)
precision_gnb = precision_score(y_test, y_pred_gnb, average='weighted')
recall_gnb = recall_score(y_test, y_pred_gnb, average='weighted')
conf_matrix_gnb = confusion_matrix(y_test, y_pred_gnb)

print("GaussianNB Performance:")
print(f'Accuracy: {accuracy_gnb * 100:.2f}%')
print(f'Precision: {precision_gnb:.2f}')
print(f'Recall: {recall_gnb:.2f}')
print('Confusion Matrix:')
print(conf_matrix_gnb)

GaussianNB Performance:
Accuracy: 97.78%
Precision: 0.98
Recall: 0.98
Confusion Matrix:
[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]


In [22]:
# Training Logistic Regression classifier
lr = LogisticRegression(max_iter=200)
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

# Evaluating Logistic Regression performance
accuracy_lr = accuracy_score(y_test, y_pred_lr)
precision_lr = precision_score(y_test, y_pred_lr, average='weighted')
recall_lr = recall_score(y_test, y_pred_lr, average='weighted')
conf_matrix_lr = confusion_matrix(y_test, y_pred_lr)

print("\nLogistic Regression Performance:")
print(f'Accuracy: {accuracy_lr * 100:.2f}%')
print(f'Precision: {precision_lr:.2f}')
print(f'Recall: {recall_lr:.2f}')
print('Confusion Matrix:')
print(conf_matrix_lr)


Logistic Regression Performance:
Accuracy: 100.00%
Precision: 1.00
Recall: 1.00
Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [23]:
# Training Decision Tree classifier
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

# Evaluating Decision Tree performance
accuracy_dt = accuracy_score(y_test, y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt, average='weighted')
recall_dt = recall_score(y_test, y_pred_dt, average='weighted')
conf_matrix_dt = confusion_matrix(y_test, y_pred_dt)

print("\nDecision Tree Performance:")
print(f'Accuracy: {accuracy_dt * 100:.2f}%')
print(f'Precision: {precision_dt:.2f}')
print(f'Recall: {recall_dt:.2f}')
print('Confusion Matrix:')
print(conf_matrix_dt)


Decision Tree Performance:
Accuracy: 100.00%
Precision: 1.00
Recall: 1.00
Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


Comparison

In [24]:
# Brief Comparison
print("\nComparison of Classifiers:")
print(f"GaussianNB Accuracy: {accuracy_gnb * 100:.2f}%")
print(f"Logistic Regression Accuracy: {accuracy_lr * 100:.2f}%")
print(f"Decision Tree Accuracy: {accuracy_dt * 100:.2f}%")


Comparison of Classifiers:
GaussianNB Accuracy: 97.78%
Logistic Regression Accuracy: 100.00%
Decision Tree Accuracy: 100.00%
